repos:
    - repo: local
      hooks:
          - id: format
            name: Format Code
            entry: npm run format
            language: system
            types: [ javascript, ts, svelte, css]
            files: '\.(js|svelte|ts|css)$'

          - id: lint
            name: Lint Code
            entry: npm run lint
            language: system
            types: [javascript, ts, svelte]
            files: '\.(js|svelte|ts)$'
