# More info - https://pre-commit.com/
# Testing command: pre-commit run
# Refer to README.md for installation instructions
repos:
    - repo: local
      hooks:
          - id: prettier
            name: Code Formatting with Prettier
            description: Automatically formats code using Prettier to ensure consistent styling across the project.
            entry: npm run format
            language: system
            args: []
            stages: [pre-commit]
            require_serial: false
            minimum_pre_commit_version: '0'
            pass_filenames: false

          - id: eslint
            name: JavaScript Linting with ESLint
            description: Checks JavaScript, TypeScript, and Svelte files for common issues and enforces coding standards.
            entry: npm run lint
            language: system
            args: []
            stages: [pre-commit]
            require_serial: false
            additional_dependencies: []
            minimum_pre_commit_version: '0'
            pass_filenames: false

          - id: cargo_fmt
            name: Rust Code Formatting with cargo fmt
            description: Applies Rust formatting rules to all files to ensure consistency and readability.
            entry: cargo fmt --all
            language: rust
            stages: [pre-commit]
            pass_filenames: false
            always_run: true

          - id: vite_build
            name: Vite Frontend Build Process
            description: Compiles the Vite frontend application, ensuring that the latest changes are built and ready for deployment.
            entry: npm run build
            language: system
            args: []
            stages: [pre-merge-commit]
            require_serial: false
            additional_dependencies: []
            minimum_pre_commit_version: '0'
            pass_filenames: false

          - id: cargo_build_with_clippy
            name: Rust Build and Analysis with Cargo and Clippy
            description: Builds all Rust targets and performs static analysis with Clippy to catch potential issues early.
            entry: cargo clippy --all-targets # To treat warnings as errors add: '-- -D warnings'
            language: rust
            args: []
            stages: [pre-merge-commit]
            require_serial: false
            additional_dependencies: []
            minimum_pre_commit_version: '0'
            pass_filenames: false
