# More info - https://pre-commit.com/
# Testing command: pre-commit run
# Refer to README.md on installation process
repos:
    -   repo: local
        hooks:
            -   id: format_frontend
                name: Format fronted code
                entry: npm run format
                language: system
                types: [ javascript, ts, svelte, css ]
                files: '\.(js|svelte|ts|css)$'

            -   id: lint_frontend
                name: Lint frontend code
                entry: npm run lint
                language: system
                types: [ javascript, ts, svelte ]
                files: '\.(js|svelte|ts)$'

            -   id: vite_build
                name: Build vite (frontend)
                entry: npm run build .
                language: system

            -   id: rust-fmt
                name: rust-fmt
                entry: cargo fmt -- --check
                language: system
                types: [ rust ]

            -   id: clippy
                name: clippy
                entry: cargo clippy -- -D warnings
                language: system
                types: [ rust ]
